######################################################################
# Automatically generated by qmake (3.0) pt. cze 2 13:37:49 2017
######################################################################
CONFIG += C++11
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE += -O3
QMAKE_LFLAGS_RELEASE -= -O1
QMAKE_LFLAGS_RELEASE += -O3
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += main.cpp
