######################################################################
# Automatically generated by qmake (3.0) czw. kwi 27 06:44:35 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = childProc
INCLUDEPATH += .

# Input
SOURCES += childModify.cpp
