######################################################################
# Automatically generated by qmake (3.0) czw. kwi 27 11:44:26 2017
######################################################################
CONFIG += c++11
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += vectorize.cpp
