######################################################################
# Automatically generated by qmake (3.0) czw. kwi 27 06:44:40 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += main.cpp
