######################################################################
# Automatically generated by qmake (3.0) niedz. maj 14 18:01:16 2017
######################################################################
CONFIG += c++14
TEMPLATE = app
TARGET = a.out
INCLUDEPATH += .

# Input
SOURCES += shVar.cpp
